name: WebInventoryPro

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]  # Solo usar Python 3.11

    steps:
    - uses: actions/checkout@v4

    # Configurar el entorno de Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Instalar las dependencias
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ejecutar flake8 para verificar el estilo del código
    - name: Run flake8
      run: |
        pip install flake8
        flake8 .  # Verifica todos los archivos del proyecto

    # Ejecutar pip-audit para verificar vulnerabilidades de dependencias
    - name: Run pip-audit
      run: |
        pip install pip-audit
        pip-audit  # Ejecuta la auditoría de dependencias

    # Ejecutar los tests de Django
    - name: Run Tests
      run: |
        python manage.py test

